module.exports = {
  apps: [
    {
      name: 'quantol-fastapi',
      script: 'uv',
      args: 'run uvicorn src.api.server:app --host 0.0.0.0 --port 8000',
      cwd: '/home/user0704/QuantOL',
      interpreter: 'none',
      instances: 1,
      exec_mode: 'fork',
      autorestart: true,
      watch: false,
      max_memory_restart: '1G',
      env: {
        NODE_ENV: 'development',
      },
      env_production: {
        NODE_ENV: 'production',
      },
      error_file: './logs/pm2-fastapi-error.log',
      out_file: './logs/pm2-fastapi-out.log',
      log_date_format: 'YYYY-MM-DD HH:mm:ss Z',
      merge_logs: true,
      time: true,
      wait_ready: true,
      kill_timeout: 5000,
      listen_timeout: 10000,
    },
    {
      name: 'quantol-nextjs',
      script: 'npm',
      args: 'start',
      cwd: '/home/user0704/QuantOL/landing-page',
      interpreter: 'none',
      instances: 1,
      exec_mode: 'fork',
      autorestart: true,
      watch: false,
      max_memory_restart: '500M',
      env: {
        NODE_ENV: 'development',
        PORT: 3000,
      },
      env_production: {
        NODE_ENV: 'production',
        PORT: 3000,
      },
      error_file: './logs/pm2-nextjs-error.log',
      out_file: './logs/pm2-nextjs-out.log',
      log_date_format: 'YYYY-MM-DD HH:mm:ss Z',
      merge_logs: true,
      time: true,
      post_update: ['npm run build'],
      kill_timeout: 5000,
    },
    {
      name: 'quantol-streamlit',
      script: 'uv',
      args: 'run streamlit run main.py --server.port 8501',
      cwd: '/home/user0704/QuantOL',
      interpreter: 'none',
      instances: 1,
      exec_mode: 'fork',
      autorestart: true,
      watch: false,
      max_memory_restart: '2G',
      env: {
        NODE_ENV: 'development',
      },
      env_production: {
        NODE_ENV: 'production',
      },
      error_file: './logs/pm2-streamlit-error.log',
      out_file: './logs/pm2-streamlit-out.log',
      log_date_format: 'YYYY-MM-DD HH:mm:ss Z',
      merge_logs: true,
      time: true,
      kill_timeout: 5000,
    },
    {
      name: 'quantol-nginx',
      script: 'nginx',
      args: '-c /home/user0704/QuantOL/nginx.conf -p /home/user0704/QuantOL',
      interpreter: 'none',
      instances: 1,
      exec_mode: 'fork',
      autorestart: true,
      watch: false,
      env: {
        NODE_ENV: 'development',
      },
      env_production: {
        NODE_ENV: 'production',
      },
      error_file: './logs/pm2-nginx-error.log',
      out_file: './logs/pm2-nginx-out.log',
      log_date_format: 'YYYY-MM-DD HH:mm:ss Z',
      merge_logs: true,
      time: true,
      kill_timeout: 3000,
      stop_signal: 'SIGQUIT',
    },
  ],
};
